version: "3.8"

services:
    db:
        image: postgres:14.7-alpine
        container_name: task-manager-db
        environment:
            POSTGRES_DB: db
            POSTGRES_USER: db-user
            POSTGRES_PASSWORD: db-password
        ports:
            - "5101:5432"
        volumes: 
            - ./postgres-data:/var/lib/postgresql/data
            - ./postgres-share:/var/db-share
        networks:
            - network-task-manager
            
            
networks:
  network-task-manager:
    name: network-task-manager-01
    driver: bridge